In [1]:
import numpy as np

In [2]:
arr = np.arange(1,21).reshape(4,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [3]:
arr2 = np.arange(101,121).reshape(4,5)
arr2

array([[101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110],
       [111, 112, 113, 114, 115],
       [116, 117, 118, 119, 120]])

In [4]:
np.concatenate((arr, arr2))

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110],
       [111, 112, 113, 114, 115],
       [116, 117, 118, 119, 120]])

In [5]:
np.concatenate((arr,arr2), axis = 1)

array([[  1,   2,   3,   4,   5, 101, 102, 103, 104, 105],
       [  6,   7,   8,   9,  10, 106, 107, 108, 109, 110],
       [ 11,  12,  13,  14,  15, 111, 112, 113, 114, 115],
       [ 16,  17,  18,  19,  20, 116, 117, 118, 119, 120]])

In [6]:
np.vstack((arr,arr2))

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110],
       [111, 112, 113, 114, 115],
       [116, 117, 118, 119, 120]])

In [9]:
np.split(arr, 2)     # can split comman equal parts

[array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])]

In [11]:
#np.split(arr, 2, axis = 1)  # raise error because not equal parts