In [1]:
import numpy as np

In [2]:
arr = np.array([10,20,30,40])
arr

array([10, 20, 30, 40])

In [3]:
arr2 = np.arange(1,11)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr.dtype

dtype('int32')

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr.size

4

In [7]:
arr2.size

10

In [8]:
len(arr)

4

In [9]:
arr.shape

(4,)

In [10]:
arr_1s = np.ones((3,4))
arr_1s

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
arr_1s.ndim

2

In [12]:
arr_1s.shape

(3, 4)

In [13]:
arr_0s = np.zeros((4,5))
arr_0s

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
arr_eye = np.eye(4,5)
arr_eye

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [15]:
arr = np.linspace(1, 5, 7)
arr

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        ])

In [16]:
arr = np.arange(1,13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [17]:
arr_2d = arr.reshape(3,4)
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [19]:
arr_3d = np.arange(1,33).reshape(4, 2, 4)
arr_3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[25, 26, 27, 28],
        [29, 30, 31, 32]]])

In [20]:
arr_3d.ndim

3

In [21]:
arr_3d.ravel()
# convert mulyi dimensional into 1D array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [22]:
arr_3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[25, 26, 27, 28],
        [29, 30, 31, 32]]])

In [23]:
arr_3d.flatten('C')
#convert array row wise into 1D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [24]:
arr_3d.flatten('F')

array([ 1,  9, 17, 25,  5, 13, 21, 29,  2, 10, 18, 26,  6, 14, 22, 30,  3,
       11, 19, 27,  7, 15, 23, 31,  4, 12, 20, 28,  8, 16, 24, 32])

In [25]:
arr_2d.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [26]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
arr_2d.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

### Accessing Elements

In [28]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
arr_2d[1,2]

7

In [30]:
arr_2d[:, 0]

array([1, 5, 9])

In [31]:
arr_2d[:, 1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [32]:
arr_3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[25, 26, 27, 28],
        [29, 30, 31, 32]]])

In [33]:
arr_3d[0,0,1]

2

In [34]:
arr_3d[2,1,1]

22

In [35]:
arr_3d[:, :, 1:3]

array([[[ 2,  3],
        [ 6,  7]],

       [[10, 11],
        [14, 15]],

       [[18, 19],
        [22, 23]],

       [[26, 27],
        [30, 31]]])

In [36]:
arr_4d = np.arange(1,361).reshape(3,4,5,6)
arr_4d

array([[[[  1,   2,   3,   4,   5,   6],
         [  7,   8,   9,  10,  11,  12],
         [ 13,  14,  15,  16,  17,  18],
         [ 19,  20,  21,  22,  23,  24],
         [ 25,  26,  27,  28,  29,  30]],

        [[ 31,  32,  33,  34,  35,  36],
         [ 37,  38,  39,  40,  41,  42],
         [ 43,  44,  45,  46,  47,  48],
         [ 49,  50,  51,  52,  53,  54],
         [ 55,  56,  57,  58,  59,  60]],

        [[ 61,  62,  63,  64,  65,  66],
         [ 67,  68,  69,  70,  71,  72],
         [ 73,  74,  75,  76,  77,  78],
         [ 79,  80,  81,  82,  83,  84],
         [ 85,  86,  87,  88,  89,  90]],

        [[ 91,  92,  93,  94,  95,  96],
         [ 97,  98,  99, 100, 101, 102],
         [103, 104, 105, 106, 107, 108],
         [109, 110, 111, 112, 113, 114],
         [115, 116, 117, 118, 119, 120]]],


       [[[121, 122, 123, 124, 125, 126],
         [127, 128, 129, 130, 131, 132],
         [133, 134, 135, 136, 137, 138],
         [139, 140, 141, 142, 143, 144],
      

In [37]:
arr_5d = np.arange(1,361).reshape(2,4,3,5,3)
arr_5d

array([[[[[  1,   2,   3],
          [  4,   5,   6],
          [  7,   8,   9],
          [ 10,  11,  12],
          [ 13,  14,  15]],

         [[ 16,  17,  18],
          [ 19,  20,  21],
          [ 22,  23,  24],
          [ 25,  26,  27],
          [ 28,  29,  30]],

         [[ 31,  32,  33],
          [ 34,  35,  36],
          [ 37,  38,  39],
          [ 40,  41,  42],
          [ 43,  44,  45]]],


        [[[ 46,  47,  48],
          [ 49,  50,  51],
          [ 52,  53,  54],
          [ 55,  56,  57],
          [ 58,  59,  60]],

         [[ 61,  62,  63],
          [ 64,  65,  66],
          [ 67,  68,  69],
          [ 70,  71,  72],
          [ 73,  74,  75]],

         [[ 76,  77,  78],
          [ 79,  80,  81],
          [ 82,  83,  84],
          [ 85,  86,  87],
          [ 88,  89,  90]]],


        [[[ 91,  92,  93],
          [ 94,  95,  96],
          [ 97,  98,  99],
          [100, 101, 102],
          [103, 104, 105]],

         [[106, 107, 108],
          

In [38]:
arr_6d = np.arange(1,5041).reshape(3,4,4,3,7,5)
arr_6d

array([[[[[[   1,    2,    3,    4,    5],
           [   6,    7,    8,    9,   10],
           [  11,   12,   13,   14,   15],
           ...,
           [  21,   22,   23,   24,   25],
           [  26,   27,   28,   29,   30],
           [  31,   32,   33,   34,   35]],

          [[  36,   37,   38,   39,   40],
           [  41,   42,   43,   44,   45],
           [  46,   47,   48,   49,   50],
           ...,
           [  56,   57,   58,   59,   60],
           [  61,   62,   63,   64,   65],
           [  66,   67,   68,   69,   70]],

          [[  71,   72,   73,   74,   75],
           [  76,   77,   78,   79,   80],
           [  81,   82,   83,   84,   85],
           ...,
           [  91,   92,   93,   94,   95],
           [  96,   97,   98,   99,  100],
           [ 101,  102,  103,  104,  105]]],


         [[[ 106,  107,  108,  109,  110],
           [ 111,  112,  113,  114,  115],
           [ 116,  117,  118,  119,  120],
           ...,
           [ 126,  127,  

In [39]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [40]:
arr[3] = 50

In [41]:
arr

array([ 1,  2,  3, 50,  5,  6,  7,  8,  9, 10, 11, 12])

In [42]:
arr_2d

array([[ 1,  2,  3, 50],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [43]:
arr_2d[0]

array([ 1,  2,  3, 50])

In [44]:
arr_3d[0][1,3]

8