In [1]:
import numpy as np

In [2]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(2,11).reshape(3,3)
arr1, arr2

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[ 2,  3,  4],
        [ 5,  6,  7],
        [ 8,  9, 10]]))

In [3]:
np.add(arr1,arr2)

array([[ 3,  5,  7],
       [ 9, 11, 13],
       [15, 17, 19]])

In [4]:
arr1 + arr2

array([[ 3,  5,  7],
       [ 9, 11, 13],
       [15, 17, 19]])

In [5]:
np.subtract(arr1,arr2)

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

In [6]:
arr1 - arr2

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

In [7]:
np.multiply(arr1,arr2)

array([[ 2,  6, 12],
       [20, 30, 42],
       [56, 72, 90]])

In [8]:
arr1 * arr2

array([[ 2,  6, 12],
       [20, 30, 42],
       [56, 72, 90]])

In [9]:
np.divide(arr2, arr1)

array([[2.        , 1.5       , 1.33333333],
       [1.25      , 1.2       , 1.16666667],
       [1.14285714, 1.125     , 1.11111111]])

In [10]:
arr2 / arr1

array([[2.        , 1.5       , 1.33333333],
       [1.25      , 1.2       , 1.16666667],
       [1.14285714, 1.125     , 1.11111111]])

In [11]:
np.dot(arr1, arr2)

array([[ 36,  42,  48],
       [ 81,  96, 111],
       [126, 150, 174]])

In [12]:
arr1 @ arr2

array([[ 36,  42,  48],
       [ 81,  96, 111],
       [126, 150, 174]])

In [13]:
np.max(arr1)

9

In [14]:
arr1.max()

9

In [15]:
np.max(arr1, axis = 1)

array([3, 6, 9])

In [16]:
np.max(arr1, axis = 0)

array([7, 8, 9])

In [18]:
np.min(arr1)

1

In [21]:
np.argmax(arr1)           #gives index of max values

8

In [22]:
np.argmin(arr1)

0

In [23]:
np.sum(arr1)

45

In [26]:
np.mean(arr1)

5.0

In [32]:
arr3 = np.array([3,4,6,7])
np.mean(arr3)

5.0

In [25]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [28]:
np.exp(arr1)         # e : Euler's number = 2.718281

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [29]:
np.std(arr1)

2.581988897471611

In [30]:
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [31]:
np.log10(arr1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])