In [1]:
import numpy as np

In [2]:
arr = np.random.random()
arr

0.16664738401577162

In [3]:
arr2 = np.random.random(5)
arr2

array([0.50252222, 0.98444863, 0.04998156, 0.67029068, 0.40107685])

In [4]:
arr3 = np.random.random((5,4))    # for n dimension give values in tuple
arr3

array([[0.20305099, 0.87769352, 0.13298791, 0.87278334],
       [0.22702282, 0.87722535, 0.09412348, 0.68382535],
       [0.2750072 , 0.09297667, 0.16925981, 0.07846298],
       [0.58904787, 0.11995299, 0.89374237, 0.31823375],
       [0.43728247, 0.4332836 , 0.71853947, 0.96196809]])

In [5]:
arr4 = np.random.randint(1,100)
arr4

85

In [6]:
arr5 = np.random.randint(1,100, (3,5))
arr5

array([[90, 83, 86, 35, 94],
       [80, 98, 62, 50, 28],
       [68, 96, 23, 92,  3]])

In [7]:
np.random.rand(3,3)    # 0 to 1

array([[0.31733612, 0.76479567, 0.63430802],
       [0.22707145, 0.59636518, 0.97459676],
       [0.33660283, 0.6634875 , 0.66159632]])

In [8]:
np.random.randn(3,3)    # Bell curve - uniformally distributed

array([[-0.60975121,  0.74044421,  0.80652627],
       [-0.20000692, -0.84748443, -0.32628048],
       [-0.59599764,  0.00491746, -0.11970354]])

In [20]:
np.random.choice(np.arange(1,7))

2

In [15]:
np.random.permutation(np.arange(1,4))

array([2, 3, 1])